---
- name: copy docker-compose file
  copy:
    src: "{{ path }}/docker-compose.yml"
    dest: /home/ubuntu/docker-compose.yml

- name: copy docker-compose file
  command: bash -c "docker pull underr/fizzbuzz:latest"

- name: start application 
  command: bash -c "docker-compose up -d"
